### PR TITLE
Add verification of plugins and dependencies via com.github.vlsi.checksum-dependency

### PR DESCRIPTION
**Pull request by vlsi**
See https://github.com/ben-manes/caffeine/issues/301#issuecomment-467731577

This enables to verify checksums before they got used (e.g. before plugins are activated), so it would prevent `stealing a coordinate` issues.

### CODE REVIEW

**Comment by ben-manes** [comment]
Very nice! What are the steps to add/update a dependency?

**Comment by vlsi** [comment]
> Very nice! What are the steps to add/update a dependency?

The idea is it fails on the first "unknown file" or "invalid file", and it prints its checksum.
That ensures no class from "bad files" is ever loaded.

Additionally the plugin saves "current `checksum.properties` file + missing checksums" to `build/checksum/computed.checksum.properties` file.

Here's a sample failure
https://travis-ci.org/trezor/trezor-android/builds/566877002#L2820-L2821

Gradle batches resolution, so it might identify 10 violations at once: https://travis-ci.org/trezor/trezor-android/builds/566844313#L1931

There's an option to `print violations as warnings`, then it would just build all the things and you have `computed.checksum.properties` with all the new items.

There's `allDependencies` task which basically runs out-of-the-box `dependencies` in each subproject, thus it triggers Gradle's resolution.


Suggestions are welcome, however I think behind the lines of implementing a CI mode that would fail just once right after build finish.

On the other hand, they say some sort of support for checksum/verification in Gradle is coming: https://github.com/gradle/gradle/issues/5633#issuecomment-517607503

**Comment by ben-manes** [comment]
Nifty. Let's give it a try. If it becomes troublesome we'll revisit, but it seemed easy enough to update when the dependency list changed.

I cherry-picked the commit, which didn't close this I guess.

**Comment by ben-manes** [comment]
oh, CI noticed that it picked up the wrong version of PMD in the computed checksum, vs the actual one. Yet `allDependencies` does show `6.17.0` on the list. Same when I try other analyzer tasks. I added them for now, but I may remove this if we can't work out an improvement.

1. I think computing needs to evaluate all projects and all dependencies, like the gradle-versions-plugin does. It sounds like you tried, but oddly some things were missed.
2. A dedicated task to update the `checksum.properties` is needed. When explicitly upgrading dependencies, I'm fine recomputing this file and the warning is if the dependency changes underneath us.
3. To counteract the concern that (2) would still let a man-in-the-middle attack, you should disallow any `http` repository url as a build check. That seems trivial.

I agree security is important. However if checks hamper development without clear benefits then it will be hard to justify. Hopefully a few tweaks will make this perfect.

```
./gradlew pmdJavaPoet pmdMain -Dpmd --console plain

239> No checksum specified for the following artifacts:
240  net.sourceforge.pmd/pmd-core/6.17.0=AF2F29C572327262E2E1ECF4223C21CE15CC794D36808521C74B2E34A541162C58A3160D5B084E0D1BA54FC7337A674FF83AE043819842B2588E8516EECE1922
241  net.sourceforge.pmd/pmd-java/6.17.0=A2360F5DFE1EB4E222FC0C8766419ED888C626144CF666917C8854BE21E8A0213D5150B6CB3040C79683ED5993163DBAA554A409A481C67433E8CCC76B0303E
242  
243  Computed checksums can be found in /home/travis/build/ben-manes/caffeine/build/checksum/computed.checksum.properties
244  Add -Pchecksum.violation.log.level=lifecycle to print all the violations not just the very first one
```

**Comment by vlsi** [comment]
> Yet allDependencies does show 6.17.0 on the list

It looks like you have recently updated PMD 6.16->6.18: https://github.com/ben-manes/caffeine/commit/e4d55348291ac97332d6ca329b4bef14730287de#diff-6512f838e273b79676cac5f72456127fR90

My PR was created before that, so the PR lists PMD 6.16, while your local env produces 6.17.

Is that the source of the difference?

> A dedicated task to update the checksum.properties is needed

Technically speaking, Gradle script can contain `if (...)` logic, so there's no generic way to figure all the possible flags to pass.

How about `--update` which would copy `computed` checksums over `/checksum.properties` file?

Then update would be like `./gradlew allDependencies --update`

**Comment by ben-manes** [comment]
A flag sounds perfect. How about also a task property to enable? I'd like to make this a CI-only check, so that it doesn't impact anyone forking the repository for their own dev work. We can restrict it to just the CI on merge for the release, so it's my burden and not theirs.

**Comment by vlsi** [comment]
>How about also a task property to enable?

Technically speaking, there's no task that performs the verification.

> I'd like to make this a CI-only check, so that it doesn't impact anyone forking the repository for their own dev work

How about adding `checksum.violation.log.level=lifecycle` to `gradle.properties` and `-Pchecksum.violation.log.level=error` for CI?

Alternative option is to wrap `apply plugin: 'com.github.vlsi.checksum-dependency'` with some sort of `if (travis detected)`

**Comment by ben-manes** [comment]
That works. If you make it so an environmental variable can be an override, rather than a project property, that is easier to configure in the CI.

**Comment by ben-manes** [comment]
oh, let me try https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties

**Comment by ben-manes** [comment]
nope, since it is nested it looks like that trick doesn't work.

**Comment by ben-manes** [comment]
okay, I used your trick to conditionally apply the plugin
```gradle
if (System.env.'CI') {
  apply plugin: 'com.github.vlsi.checksum-dependency'
}
```

**Comment by vlsi** [comment]
>okay, I used your trick to conditionally apply the plugin

I guess I can add a second name for the plugin: `com.github.vlsi.checksum-dependency-warnings-only` that would default to "warning by default", so in CI it could be configured to fail on warning (e.g. fail at the end of the build so all the discrepancies are visible)

**Comment by vlsi** [comment]
There's a side story here.
It looks like I can download `.asc` signatures as well.
Unfortunately, certain artifacts miss `.asc` signatures. For instance, Plugin Portal does not enforce `.asc`, so most of Gradle Plugins lack cryptographic signatures.

Below results are produced with zero configuration (it picked relevant buildscript/project repositories automatically). Resolving 240 of 280 is not that bad for the first try in my opinion.

As you might see it shows that certain "well-known" artifacts (e.g. antlr:2.7.7) miss asc signatures.
It might be caused by the fact that the artifact was resolved from `jcenter`, and it indeed lacks the signature: https://plugins.gradle.org/m2/antlr/antlr/2.7.7 (I'm not sure if that is the cause or not though).

It looks like use of `.asc` might simplify maintenance of dependency verification.
As of now I think behind the lines of a configuration file that lists statements like
"trust key 32387482348 for module antlr:antlr"
"trust key 32387482348 for packages in group org.acme...."
"trust key 32387482348 for all packages"

There might be interesting twists like
"packages in com.google must be signed by at least two keys ...."
"trusted keys for org.apache.commons should be taken from apache.org/commons/KEYS"
"package must be signed by a trusted key, and a warning should be produced if checksum is not in a known list".

That might escalate quite quickly, so I wonder what do you think of PGP use for verification and what could be the primary use cases?

```
caffeine $ ./gradlew allDependencies
...
Resolved 240 of 280 signatures

Missing 40 signatures:
  antlr:antlr:2.7.7@jar.asc
  aopalliance:aopalliance:1.0@jar.asc
  com.github.FastFilter:fastfilter_java:bf0b02297f@jar.asc
  com.github.ben-manes:gradle-versions-plugin:0.21.0@jar.asc
  com.github.brianfrankcooper.YCSB:core:0.15.0@jar.asc
  com.github.jengelman.gradle.plugins:shadow:5.1.0@jar.asc
  com.gradle:build-scan-plugin:2.3@jar.asc
  gradle.plugin.com.github.mjdetullio.gradle:coverity-plugin:1.0.10@jar.asc
  gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:2.0.0@jar.asc
  gradle.plugin.io.morethan.jmhreport:gradle-jmh-report:0.9.0@jar.asc
  io.ehdev:gradle-semantic-versioning:1.1.0@jar.asc
  javax.inject:javax.inject:1@jar.asc
  javax.jcr:jcr:2.0@jar.asc
  me.champeau.gradle:jmh-gradle-plugin:0.5.0-rc-2@jar.asc
  net.java.dev.javacc:javacc:5.0@jar.asc
  net.jcip:jcip-annotations:1.0@jar.asc
  net.ltgt.gradle:gradle-apt-plugin:0.21@jar.asc
  net.ltgt.gradle:gradle-errorprone-plugin:0.8.1@jar.asc
  net.ltgt.gradle:gradle-nullaway-plugin:0.3@jar.asc
  net.sf.ezmorph:ezmorph:1.0.6@jar.asc
  net.sf.json-lib:json-lib:2.3:jdk15@jar.asc
  net.sf.kxml:kxml2:2.3.0@jar.asc
  net.sourceforge.saxon:saxon:9.1.0.8:dom@jar.asc
  net.sourceforge.saxon:saxon:9.1.0.8@jar.asc
  org.codehaus.groovy.modules.http-builder:http-builder:0.7.1@jar.asc
  org.codehaus.jackson:jackson-core-asl:1.9.4@jar.asc
  org.codehaus.jackson:jackson-mapper-asl:1.9.4@jar.asc
  org.ow2.asm:asm-analysis:7.0@jar.asc
  org.ow2.asm:asm-analysis:7.1@jar.asc
  org.ow2.asm:asm-commons:7.0@jar.asc
  org.ow2.asm:asm-commons:7.1@jar.asc
  org.ow2.asm:asm-tree:7.0@jar.asc
  org.ow2.asm:asm-tree:7.1@jar.asc
  org.ow2.asm:asm-util:7.0@jar.asc
  org.ow2.asm:asm:7.0@jar.asc
  org.ow2.asm:asm:7.1@jar.asc
  xerces:xercesImpl:2.9.1@jar.asc
  xml-resolver:xml-resolver:1.2@jar.asc
  xmlpull:xmlpull:1.1.3.1@jar.asc
  xpp3:xpp3_min:1.1.4c@jar.asc
```

```
Resolved 240 signatures:
  biz.aQute.bnd:biz.aQute.bnd.gradle:4.2.0@jar.asc
  biz.aQute.bnd:biz.aQute.bndlib:4.2.0@jar.asc
  biz.aQute.bnd:biz.aQute.repository:4.2.0@jar.asc
  biz.aQute.bnd:biz.aQute.resolve:4.2.0@jar.asc
  biz.aQute.bnd:bndlib:2.4.0@jar.asc
  com.android.tools.build:builder-model:1.0.0@jar.asc
  com.android.tools.build:builder-test-api:1.0.0@jar.asc
  com.android.tools.build:builder:1.0.0@jar.asc
  com.android.tools.build:gradle:1.0.0@jar.asc
  com.android.tools.build:manifest-merger:24.0.0@jar.asc
  com.android.tools.ddms:ddmlib:24.0.0@jar.asc
  com.android.tools.external.lombok:lombok-ast:0.2.2@jar.asc
  com.android.tools.layoutlib:layoutlib-api:24.0.0@jar.asc
  com.android.tools.lint:lint-api:24.0.0@jar.asc
  com.android.tools.lint:lint-checks:24.0.0@jar.asc
  com.android.tools.lint:lint:24.0.0@jar.asc
  com.android.tools:common:24.0.0@jar.asc
  com.android.tools:dvlib:24.0.0@jar.asc
  com.android.tools:sdk-common:24.0.0@jar.asc
  com.android.tools:sdklib:24.0.0@jar.asc
  com.beust:jcommander:1.72@jar.asc
  com.bmuschko:gradle-nexus-plugin:2.3.1@jar.asc
  com.carrotsearch:hppc:0.8.1@jar.asc
  com.clearspring.analytics:stream:2.9.6@jar.asc
  com.fasterxml.jackson.core:jackson-core:2.8.11@jar.asc
  com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.8.11@jar.asc
  com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.8.11@jar.asc
  com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.8.11@jar.asc
  com.github.jbellis:jamm:0.3.3@jar.asc
  com.github.kevinstern:software-and-algorithms:1.0@jar.asc
  com.github.spotbugs:spotbugs-annotations:3.1.12@jar.asc
  com.github.spotbugs:spotbugs:3.1.12@jar.asc
  com.github.stephenc.jcip:jcip-annotations:1.0-1@jar.asc
  com.google.auto:auto-common:0.10@jar.asc
  com.google.code.findbugs:jFormatString:3.0.0@jar.asc
  com.google.code.findbugs:jsr305:3.0.2@jar.asc
  com.google.code.gson:gson:2.8.5@jar.asc
  com.google.errorprone:error_prone_annotation:2.3.3@jar.asc
  com.google.errorprone:error_prone_annotations:2.3.2@jar.asc
  com.google.errorprone:error_prone_annotations:2.3.3@jar.asc
  com.google.errorprone:error_prone_check_api:2.3.3@jar.asc
  com.google.errorprone:error_prone_core:2.3.3@jar.asc
  com.google.errorprone:error_prone_type_annotations:2.3.3@jar.asc
  com.google.errorprone:javac:9+181-r4173-1@jar.asc
  com.google.guava:failureaccess:1.0.1@jar.asc
  com.google.guava:guava-testlib:28.0-jre@jar.asc
  com.google.guava:guava:27.0.1-jre@jar.asc
  com.google.guava:guava:28.0-jre@jar.asc
  com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava@jar.asc
  com.google.inject:guice:4.2.2@jar.asc
  com.google.j2objc:j2objc-annotations:1.1@jar.asc
  com.google.j2objc:j2objc-annotations:1.3@jar.asc
  com.google.protobuf:protobuf-java:3.4.0@jar.asc
  com.google.truth:truth:0.24@jar.asc
  com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2@jar.asc
  com.googlecode.java-diff-utils:diffutils:1.3.0@jar.asc
  com.googlecode.javaewah:JavaEWAH:0.7.9@jar.asc
  com.jakewharton.fliptables:fliptables:1.0.2@jar.asc
  com.jcraft:jsch:0.1.50@jar.asc
  com.puppycrawl.tools:checkstyle:8.23@jar.asc
  com.squareup:javapoet:1.11.1@jar.asc
  com.squareup:javawriter:2.5.0@jar.asc
  com.sun.istack:istack-commons-runtime:3.0.7@jar.asc
  com.sun.xml.fastinfoset:FastInfoset:1.2.15@jar.asc
  com.tdunning:t-digest:3.2@jar.asc
  com.thoughtworks.xstream:xstream:1.4.10@jar.asc
  com.trivago:triava:2.0.1@jar.asc
  com.typesafe.akka:akka-actor_2.12:2.6.0-M5@jar.asc
  com.typesafe:config:1.3.4@jar.asc
  com.uber.nullaway:nullaway:0.7.5@jar.asc
  com.univocity:univocity-parsers:2.8.2@jar.asc
  commons-beanutils:commons-beanutils:1.8.0@jar.asc
  commons-beanutils:commons-beanutils:1.9.3@jar.asc
  commons-codec:commons-codec:1.12@jar.asc
  commons-codec:commons-codec:1.6@jar.asc
  commons-collections:commons-collections:3.2.1@jar.asc
  commons-collections:commons-collections:3.2.2@jar.asc
  commons-io:commons-io:2.6@jar.asc
  commons-lang:commons-lang:2.4@jar.asc
  commons-lang:commons-lang:2.6@jar.asc
  commons-logging:commons-logging:1.1.3@jar.asc
  info.picocli:picocli:3.9.6@jar.asc
  it.unimi.dsi:fastutil:8.3.0@jar.asc
  javax.activation:javax.activation-api:1.2.0@jar.asc
  javax.cache:cache-api:1.0.0@jar.asc
  javax.cache:cache-api:1.1.1:javadoc@jar.asc
  javax.cache:cache-api:1.1.1@jar.asc
  javax.cache:cache-tests:1.1.1:tests@jar.asc
  javax.cache:cache-tests:1.1.1@jar.asc
  javax.xml.bind:jaxb-api:2.3.1@jar.asc
  jaxen:jaxen:1.1.6@jar.asc
  joda-time:joda-time:2.10.2@jar.asc
  junit:junit:4.12@jar.asc
  net.bytebuddy:byte-buddy-agent:1.9.10@jar.asc
  net.bytebuddy:byte-buddy:1.9.10@jar.asc
  net.java.dev.jna:jna:4.1.0@jar.asc
  net.jodah:expiringmap:0.5.9@jar.asc
  net.openhft:koloboke-api-jdk8:0.6.8@jar.asc
  net.openhft:koloboke-impl-jdk8:0.6.8@jar.asc
  net.sf.jopt-simple:jopt-simple:4.6@jar.asc
  net.sf.jopt-simple:jopt-simple:5.0.2@jar.asc
  net.sf.proguard:proguard-base:5.1@jar.asc
  net.sf.proguard:proguard-gradle:5.1@jar.asc
  net.sf.saxon:Saxon-HE:9.9.1-4@jar.asc
  net.sourceforge.nekohtml:nekohtml:1.9.16@jar.asc
  net.sourceforge.pmd:pmd-core:6.17.0@jar.asc
  net.sourceforge.pmd:pmd-java:6.17.0@jar.asc
  org.antlr:antlr4-runtime:4.7.2@jar.asc
  org.antlr:antlr4-runtime:4.7@jar.asc
  org.apache-extras.beanshell:bsh:2.0b6@jar.asc
  org.apache.bcel:bcel:6.3@jar.asc
  org.apache.commons:commons-compress:1.18@jar.asc
  org.apache.commons:commons-compress:1.8.1@jar.asc
  org.apache.commons:commons-lang3:3.8.1@jar.asc
  org.apache.commons:commons-lang3:3.9@jar.asc
  org.apache.commons:commons-math3:3.2@jar.asc
  org.apache.commons:commons-math3:3.6.1@jar.asc
  org.apache.felix:org.apache.felix.framework:6.0.3@jar.asc
  org.apache.htrace:htrace-core4:4.1.0-incubating@jar.asc
  org.apache.httpcomponents:httpclient:4.3@jar.asc
  org.apache.httpcomponents:httpcore:4.3@jar.asc
  org.apache.httpcomponents:httpmime:4.3@jar.asc
  org.apache.jackrabbit:jackrabbit-api:2.18.2@jar.asc
  org.apache.jackrabbit:jackrabbit-data:2.18.2@jar.asc
  org.apache.jackrabbit:jackrabbit-jcr-commons:2.18.2@jar.asc
  org.apache.jackrabbit:oak-api:1.16.0@jar.asc
  org.apache.jackrabbit:oak-blob-plugins:1.16.0@jar.asc
  org.apache.jackrabbit:oak-blob:1.16.0@jar.asc
  org.apache.jackrabbit:oak-commons:1.16.0@jar.asc
  org.apache.jackrabbit:oak-core-spi:1.16.0@jar.asc
  org.apache.jackrabbit:oak-core:1.16.0@jar.asc
  org.apache.jackrabbit:oak-jackrabbit-api:1.16.0@jar.asc
  org.apache.jackrabbit:oak-query-spi:1.16.0@jar.asc
  org.apache.jackrabbit:oak-security-spi:1.16.0@jar.asc
  org.apache.jackrabbit:oak-store-spi:1.16.0@jar.asc
  org.apache.logging.log4j:log4j-api:2.11.1@jar.asc
  org.apache.maven.resolver:maven-resolver-api:1.3.1@jar.asc
  org.apache.maven.resolver:maven-resolver-impl:1.3.1@jar.asc
  org.apache.maven.resolver:maven-resolver-spi:1.3.1@jar.asc
  org.apache.maven.resolver:maven-resolver-util:1.3.1@jar.asc
  org.awaitility:awaitility:3.1.6@jar.asc
  org.bouncycastle:bcpkix-jdk15on:1.48@jar.asc
  org.bouncycastle:bcprov-jdk15on:1.48@jar.asc
  org.cache2k:cache2k-api:1.2.2.Final@jar.asc
  org.cache2k:cache2k-core:1.2.2.Final@jar.asc
  org.caffinitas.ohc:ohc-core-j8:0.6.1@jar.asc
  org.caffinitas.ohc:ohc-core:0.6.1@jar.asc
  org.checkerframework:checker-qual:2.10.0@jar.asc
  org.checkerframework:checker-qual:2.5.3@jar.asc
  org.checkerframework:checker-qual:2.8.1@jar.asc
  org.checkerframework:dataflow:2.5.3@jar.asc
  org.checkerframework:javacutil:2.5.3@jar.asc
  org.codehaus.groovy:groovy-backports-compat23:2.4.15@jar.asc
  org.codehaus.mojo:animal-sniffer-annotations:1.17@jar.asc
  org.dom4j:dom4j:2.1.1@jar.asc
  org.easymock:easymock:4.0.2@jar.asc
  org.eclipse.jdt.core.compiler:ecj:4.2.2@jar.asc
  org.eclipse.jgit:org.eclipse.jgit:3.6.0.201412230720-r@jar.asc
  org.ehcache:ehcache:3.8.0@jar.asc
  org.elasticsearch:elasticsearch-cli:7.3.0@jar.asc
  org.elasticsearch:elasticsearch-core:7.3.0@jar.asc
  org.elasticsearch:elasticsearch-geo:7.3.0@jar.asc
  org.elasticsearch:elasticsearch-secure-sm:7.3.0@jar.asc
  org.elasticsearch:elasticsearch-x-content:7.3.0@jar.asc
  org.elasticsearch:elasticsearch:7.3.0@jar.asc
  org.elasticsearch:jna:4.5.1@jar.asc
  org.glassfish.jaxb:jaxb-runtime:2.3.1@jar.asc
  org.glassfish.jaxb:txw2:2.3.1@jar.asc
  org.hamcrest:hamcrest-core:1.3@jar.asc
  org.hamcrest:hamcrest-library:1.3@jar.asc
  org.hamcrest:hamcrest:2.1@jar.asc
  org.hdrhistogram:HdrHistogram:2.1.4@jar.asc
  org.hdrhistogram:HdrHistogram:2.1.9@jar.asc
  org.jacoco:org.jacoco.agent:0.8.4@jar.asc
  org.jacoco:org.jacoco.ant:0.8.4@jar.asc
  org.jacoco:org.jacoco.core:0.8.4@jar.asc
  org.jacoco:org.jacoco.report:0.8.4@jar.asc
  org.jctools:jctools-core:2.1.2@jar.asc
  org.jetbrains.kotlin:kotlin-stdlib:1.1.2-3@jar.asc
  org.jetbrains:annotations:13.0@jar.asc
  org.jetbrains:annotations:16.0.3@jar.asc
  org.jsr107.ri:cache-annotations-ri-common:1.1.1@jar.asc
  org.jsr107.ri:cache-annotations-ri-guice:1.1.1@jar.asc
  org.jvnet.staxex:stax-ex:1.8@jar.asc
  org.kordamp.gradle:stats-gradle-plugin:0.2.2@jar.asc
  org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.8.3@jar.asc
  org.mockito:mockito-core:3.0.0@jar.asc
  org.objenesis:objenesis:2.6@jar.asc
  org.objenesis:objenesis:3.0.1@jar.asc
  org.openjdk.jmh:jmh-core:1.21@jar.asc
  org.openjdk.jmh:jmh-generator-asm:1.21@jar.asc
  org.openjdk.jmh:jmh-generator-bytecode:1.21@jar.asc
  org.openjdk.jmh:jmh-generator-reflection:1.21@jar.asc
  org.openjdk.jol:jol-cli:0.9@jar.asc
  org.openjdk.jol:jol-core:0.9@jar.asc
  org.ops4j.base:ops4j-base-io:1.5.0@jar.asc
  org.ops4j.base:ops4j-base-lang:1.5.0@jar.asc
  org.ops4j.base:ops4j-base-monitors:1.5.0@jar.asc
  org.ops4j.base:ops4j-base-net:1.5.0@jar.asc
  org.ops4j.base:ops4j-base-spi:1.5.0@jar.asc
  org.ops4j.base:ops4j-base-store:1.5.0@jar.asc
  org.ops4j.base:ops4j-base-util-property:1.5.0@jar.asc
  org.ops4j.pax.exam:pax-exam-container-native:4.13.1@jar.asc
  org.ops4j.pax.exam:pax-exam-junit4:4.13.1@jar.asc
  org.ops4j.pax.exam:pax-exam-link-mvn:4.13.1@jar.asc
  org.ops4j.pax.exam:pax-exam-spi:4.13.1@jar.asc
  org.ops4j.pax.exam:pax-exam:4.13.1@jar.asc
  org.ops4j.pax.swissbox:pax-swissbox-core:1.8.2@jar.asc
  org.ops4j.pax.swissbox:pax-swissbox-lifecycle:1.8.2@jar.asc
  org.ops4j.pax.swissbox:pax-swissbox-optional-jcl:1.8.2@jar.asc
  org.ops4j.pax.swissbox:pax-swissbox-property:1.8.2@jar.asc
  org.ops4j.pax.swissbox:pax-swissbox-tracker:1.8.2@jar.asc
  org.ops4j.pax.tinybundles:tinybundles:2.1.1@jar.asc
  org.ops4j.pax.url:pax-url-aether-support:2.6.1@jar.asc
  org.ops4j.pax.url:pax-url-aether:2.6.1@jar.asc
  org.ops4j.pax.url:pax-url-classpath:2.4.5@jar.asc
  org.ops4j.pax.url:pax-url-commons:2.4.5@jar.asc
  org.ops4j.pax.url:pax-url-link:2.4.5@jar.asc
  org.osgi:org.osgi.service.component.annotations:1.3.0@jar.asc
  org.osgi:org.osgi.service.metatype.annotations:1.3.0@jar.asc
  org.ow2.asm:asm-analysis:4.0@jar.asc
  org.ow2.asm:asm-tree:4.0@jar.asc
  org.ow2.asm:asm:4.0@jar.asc
  org.ow2.asm:asm:5.0.3@jar.asc
  org.pcollections:pcollections:2.1.2@jar.asc
  org.scala-lang.modules:scala-java8-compat_2.12:0.8.0@jar.asc
  org.scala-lang:scala-library:2.12.8@jar.asc
  org.slf4j:jcl-over-slf4j:1.6.6@jar.asc
  org.slf4j:jcl-over-slf4j:1.7.26@jar.asc
  org.slf4j:slf4j-api:1.7.25@jar.asc
  org.slf4j:slf4j-api:1.7.26@jar.asc
  org.slf4j:slf4j-api:1.8.0-beta4@jar.asc
  org.slf4j:slf4j-nop:1.7.25@jar.asc
  org.slf4j:slf4j-simple:1.8.0-beta4@jar.asc
  org.sonarsource.scanner.api:sonar-scanner-api:2.12.0.1661@jar.asc
  org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.7.1@jar.asc
  org.testng:testng:6.14.3@jar.asc
  org.tukaani:xz:1.8@jar.asc
  org.yaml:snakeyaml:1.17@jar.asc
  systems.comodal:collision:0.3.3@jar.asc
```

**Comment by vlsi** [comment]
Oh, I have double-checked, and org.ow2.asm:asm:7.0 and org.ow2.asm:asm:7.1 indeed lack PGP signing even for the official releases (https://asm.ow2.io/ -> https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/ )
I've requested PGP from ASM via https://gitlab.ow2.org/asm/asm/issues/317878 

In other words, it looks like "missing 40 signatures" seems to be accurate (in other words, that artifacts indeed lack `.asc` publications)

**Comment by ben-manes** [comment]
yes, unfortunately it isn't required. If you use another build tool, like Ant, it is trivial to forget.

**Comment by vlsi** [comment]
I thought Maven Central had a strict requirement that each upload should be PGP-signed.

It looks like ASM uses their own repository which has no such a requirement, and Maven Central blindly fetches from repository.ow2.org

So, what do you think re PGP-driven verification?
Is "PGP or SHA" a good start?

**Comment by ben-manes** [comment]
I do think PGP verification is ideal, since it was built into Maven's release process. I do think any verification is a bit hard since the Maven never pushed forward there, letting it be ad hoc across the board.

**Pull request closed without merging**
