### PR TITLE
fix a wrong argument check while configure recordStats by CaffeineSpec

### PR DESCRIPTION
**Pull request by justgame**

### CODE REVIEW

**Comment by ben-manes** [comment]
Are you sure? This asserts that there is no value par (e.g. `recordStats=true`). The condition that `value == null` is asserted. See `CaffeineSpecTest` for the unit test.

**Comment by justgame** [comment]
I'm not so sure. I just configure caffeine in a springboot project, and use `spring.cache.caffeine.spec=recordStats=true,maximumSize=5000,expireAfterAccess=600s`, then it throws a   IllegalArgumentException with message "record stats does not take a value"

**Comment by ben-manes** [comment]
Right, the stats (as originally defined by Guava) would be

```
spring.cache.caffeine.spec=recordStats,maximumSize=5000,expireAfterAccess=600s
```

**Comment by justgame** [comment]
Sorry, it's my fault. Thank you for your explanation.

**Comment by ben-manes** [comment]
No problem, it is a little confusing. Maybe we could make it optionally handle true/false in the future.

**Pull request closed without merging**
