### PR TITLE
Added a note about camel-caffeine

### PR DESCRIPTION
**Pull request by oscerd**
Just a little note about the camel-caffeine component in Camel.

https://github.com/apache/camel/tree/master/components/camel-caffeine

### CODE REVIEW

**Comment by ben-manes** [comment]
Maybe we should have Camel in both sections? One is for projects using it internally, the other is for integrations for consumers to take advantage of. Camel is in both. Or perhaps we should include Camel only in the latter since that's more meaningful to users? If you render the README, you'll see its kind of a mess with this change due to how verbose the combined phrasing is.

I guess I'd favor either leaving it as is, or moving Camel into the other section and linking to the documentation of `camel-caffeine` rather than the project. Thoughts?

**Comment by oscerd** [comment]
I guess the origin position for Camel is good as is, maybe adding a note about camel-caffeine somewhere in the docs can be useful too.

**Comment by ben-manes** [comment]
How about I we move it to the other section and change the link to,
https://github.com/apache/camel/blob/master/components/camel-caffeine/src/main/docs/caffeine-cache-component.adoc

Presumably that's useful for users and we should be more interesting in advertising that extension than an implementation detail.

**Comment by oscerd** [comment]
Do you mean something like this?

**Comment by ben-manes** [comment]
I made a tad simpler change, if that's okay.

**Comment by oscerd** [comment]
Great thanks :-)

**Pull request closed without merging**
