### PR TITLE
Add StackOverflow badge with link to tag

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by ben-manes** [comment]
I'm afraid that this might make the README too busy. It seems that people find their way to the issue tracker, email, or SO already so the hint may not be necessary.

**Comment by valery1707** [comment]
Only some people's questions may be a real bug that need to be added in issue tracker. Questions asked by email is not so bad, but it not public and other people with same question will be ask it again and again.
Link to SO can show appropriate way to ask questions about project. If SO is really appropriate way :)

**Comment by ben-manes** [comment]
cherry-picked onto master, thanks.

**Comment by valery1707** [comment]
Thanks

**Pull request closed without merging**
