### PR TITLE
Gil

### PR DESCRIPTION
**Pull request by gilga1983**
fixed according to coding style and editing comments by Ben.

### CODE REVIEW

**Comment by ben-manes** [comment]
I cleaned up your branch. Can you please take a look at let me know if the changes are okay? If so then I can merge it in.

Note that you didn't wire the new `TinyCacheAdmission` class for the simulator. I can do this if you tell me what the `nrSets` and `itemsPerSet` constructor values should be set to (e.g. config file defaults). Would you want your version and the CountMinSketch to both be evaluated with, or should the count-min version be removed?

fyi I deleted the `simulator/TinyCache/*` files (e.g. `NewTinyCache` since that looked like a temporary directory used for porting. It wasn't part of the project so neither the build or Eclipse saw it.

**Comment by gilga1983** [comment]
Well it is not ready yet. I was working on it before and then lost momentum
I hope to get it ready soon enough.

On Tue, Aug 18, 2015 at 10:01 PM, Ben Manes <notifications@github.com>
wrote:

> I cleaned up your branch. Can you please take a look at let me know if the
> changes are okay? If so then I can merge it in.
>
> Note that you didn't wire the new TinyCacheAdmission class for the
> simulator. I can do this if you tell me what the nrSets and itemsPerSet
> constructor values should be set to (e.g. config file defaults). Would you
> want your version and the CountMinSketch to both be evaluated with, or
> should the count-min version be removed?
>
> fyi I deleted the simulator/TinyCache/* files (e.g. NewTinyCache since
> that looked like a temporary directory used for porting. It wasn't part of
> the project so neither the build or Eclipse saw it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ben-manes/caffeine/pull/25#issuecomment-132333453>.
>



-- 
Thanks
Gil Einziger (aka Gilga)

**Comment by ben-manes** [comment]
Okay, do you want this merged in as is or do you plan on continuing to work on this pull request?

**Comment by gilga1983** [comment]
Not right now, when I am ready I'll work on merging it.


On Wed, Aug 19, 2015 at 8:29 AM, Ben Manes <notifications@github.com> wrote:

> Okay, do you want this merged in as is or do you plan on continuing to
> work on this pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ben-manes/caffeine/pull/25#issuecomment-132461672>.
>



-- 
Thanks
Gil Einziger (aka Gilga)

**Comment by ben-manes** [comment]
oh okay. In the future no need to send a pull request until you want it reviewed

**Comment by ben-manes** [comment]
I'm looking forward to playing with this. I think this is based on your tiny table, right? I'd like to see the performance gain of this scheme in your tinylfu (memory & cpu costs). If I shouldn't have deleted the `TinyCache` let me know and I can revert them back into the branch.

Also, let me know if you have ideas for a better name for the `EdenQueue`.

**Comment by gilga1983** [comment]
Ben,  I still have some delicate bugs in there. I am continuing to debug in
my own project and I'll port it when I am done. Yes it is based on,
TinyTable.


On Thu, Sep 3, 2015 at 12:10 PM, Ben Manes <notifications@github.com> wrote:

> I'm looking forward to playing with this. I think this is based on your
> tiny table, right? I'd like to see the performance gain of this scheme in
> your tinylfu (memory & cpu costs). If I shouldn't have deleted the
> TinyCache let me know and I can revert them back into the branch.
>
> Also, let me know if you have ideas for a better name for the EdenQueue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ben-manes/caffeine/pull/25#issuecomment-137400275>.
>



-- 
Thanks
Gil Einziger (aka Gilga)

**Comment by ben-manes** [comment]
Closing. Please open a new pull request when a `TinyTable` version is ready. It sounds like you won't have time for now and the 4-bit `CountMinSketch` is pretty good for the time being.

**Comment by gilga1983** [comment]
oh... I did not realize it was still open. I saw that it did some bugs and
moved it back to testing. I do not have many hours to code nowadays but
I'll get there.


On Mon, Sep 21, 2015 at 7:41 PM, Ben Manes <notifications@github.com> wrote:

> Closed #25 <https://github.com/ben-manes/caffeine/pull/25>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ben-manes/caffeine/pull/25#event-415019373>.
>



-- 
Thanks
Gil Einziger (aka Gilga)

**Comment by ben-manes** [comment]
No worries! I think we're in a pretty good spot right now, but it will be cool to try out your TinyTable when you have the bandwidth.

**Pull request closed without merging**
