### PR TITLE
new sample

### PR DESCRIPTION
**Pull request by sheepdreamofandroids**
It took a while, but here's the sample of batching loads for #309

### CODE REVIEW

**Comment by ben-manes** [comment]
Thanks @sheepdreamofandroids!

I'm curious about the `load(Map)` method. From a user's perspective, I imagine it might be cleaner to return the futures instead of consume them. There could be all sorts of bugs, such as that method throwing an exception. I imagine in practice you have more edge case handling and tried to be minimal here for the clearest demonstration? My concern is that someone might just copy it as-is and get bitten.

**Comment by sheepdreamofandroids** [comment]
Well, I wrote this from scratch since it turned out that there are just too many business logic concerns in the current code. I put this PR out here to get exactly this kind of feedback. 

load() has this signature because the underlying bulk call usually associates keys with values in one of two ways: either it returns each value together with the key, or it returns the values in the same order as the keys.

I tried to make both ways possible in the same call without forcing the user to create a map or reorder values.

Thinking about it, I could probably allow different lambda's to be passed in the constructor to allow for both ways.

**Comment by Maaartinus** [comment]
> either it returns each value together with the key, or it returns the values in the same order as the keys.

Another pretty common case may be returning the values unsorted, but knowing how to get the key from the value. This is the case with simple `SELECT ... FROM ... WHERE id in (....)`.

**Comment by sheepdreamofandroids** [comment]
> Another pretty common case may be returning the values unsorted, but knowing how to get the key from the value. This is the case with simple `SELECT ... FROM ... WHERE id in (....)`.

True. And now that I can have different types of wrapped loaders, nothing stops me from supporting that explicitly ;-)

**Comment by sheepdreamofandroids** [comment]
> Another pretty common case may be returning the values unsorted, but knowing how to get the key from the value. This is the case with simple `SELECT ... FROM ... WHERE id in (....)`.

@Maaartinus Is this what you had in mind?

**Comment by ben-manes** [comment]
Sorry that I haven't had the time to merge this. It's on my backlog, so maybe I'll have the energy next weekend to work on these things.

**Comment by sheepdreamofandroids** [comment]
No worries!

Life just won't adapt to GitHub...

**Comment by ben-manes** [comment]
Sorry for the long delay. I had been considering to refactor things a bit in the handoff, but that was leaving this linger. So I tried to merge it and run, but unfortunately the tests failed.

```
Running com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest
whenEnoughKeysAreRequestedTheLoadWillHappenImmediately[0](com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest) failed, 2 attempts left.
maxDelayIsNotMissedTooMuch[2](com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest) failed, 2 attempts left.
maxDelayIsNotMissedTooMuch[2](com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest) failed, 1 attempts left.
maxDelayIsNotMissedTooMuch[2](com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest) failed, 0 attempts left.
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.706 sec <<< FAILURE!
maxDelayIsNotMissedTooMuch[2](com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest)  Time elapsed: 0.215 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <1>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.github.benmanes.caffeine.examples.coalescing.bulkloader.CoalescingBulkloaderTest.maxDelayIsNotMissedTooMuch(CoalescingBulkloaderTest.java:98)
```

**Comment by ben-manes** [comment]
Sorry, this was closed by accident and I can't reopen..

**Pull request merged**
