### PR TITLE
Including the Rapidoid cache into the benchmarks.

### PR DESCRIPTION
**Pull request by nmihajlovski**

### CODE REVIEW

**Comment by ben-manes** [comment]
Nice! 👍 
Sorry, I completely forgot that I promised to take a stab at this too.

**Comment by nmihajlovski** [comment]
No worries, I was happy to contribute a bit. :) I finally found the time to do it.

**Comment by ben-manes** [comment]
Do you want to add this to the Simulator as well? That shows the hit rate efficiencies.

**Comment by nmihajlovski** [comment]
That would be nice, unless it's time-consuming, so I would consider it as optional.

**Comment by ben-manes** [comment]
It looks like `Caching.shutdown()` isn't needed anymore, because you no longer schedule the crawler if the TTL is not set. In the benchmarks they call `cleanUp` during the setup, so it would have been turned off. But since its not loaded, I don't see any of the Rapidoid logging spamming the output. So I think I can remove that line?

**Comment by ben-manes** [comment]
I amended the simulator addition to your commit and merged. Thanks!

**Comment by nmihajlovski** [comment]
That's correct - `Caching.shutdown()` isn't needed if TTL isn't set. Thanks for the help!

**Pull request closed without merging**
